version: 0.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
before_build:
- cmd: nuget restore
build:
  project: GraficRedactor.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

after_build:
- cmd: >-
    cd packages\Tools.InnoSetup.5.5.6\tools

 
    iscc "..\..\install.iss"
    
    

artifacts:
- path: Installator

deploy:
  release: GraficRedactor-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: VgFAgpMigUV1l0YOGII/2Ot6OCtBwBZBaFaLcTeswSD3LigGSsOqX+txrNrz62lW
  on:
    configuration: Release
    branch: master
    